### ISSUE TITLE
Windows users cannot clone

### ISSUE THREAD

**Issue by shreybohra** [icl-rocketry/art-sims#1]
file structure is illegally long :(

errors returned when cloning this dir: https://github.com/icl-rocketry/art-sims/tree/main/MATLAB/OpenRocket%20Data%20Analysis/FlightEvents/for_redistribution_files_only/FlightEvents.app/Contents/Resources/FlightEvents_mcr/.matlab/toolbox/matlab/maps/supportpackages/bluegreenbasemapdata/mapdata/maptiles/NaturalEarth/bluegreen/v1/6/30

if not in use remove it from the repo/add to .gitignore?

**Comment by NathanaelJ** [comment]
Removed this file - FlightEvents served no purpose.
